In [66]:
# import required libraries
import pandas as pd
import numpy as np 
import random

In [14]:
Game = pd.read_csv('./Games.csv')
Game_origin = pd.read_csv('../game with ratings/Games.csv')
Game_sales_origin = pd.read_csv('../game sales with image from vg/game_sales_with_image.csv')
Game_reviews_origin = pd.read_csv('../game reviews from vandal/game_reviews.csv')

In [15]:
Game_origin

,id,slug,name,metacritic,released,tba,updated,website,rating,rating_top,...,developers,genres,publishers,esrb_rating,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
0,1,dgeneration-hd,D/Generation HD,NaN,2015-10-23,False,2019-09-17T11:58:57,http://dgeneration.net,0.0,0,...,West Coast Software||West Coast Software Limited,Adventure||Puzzle,West Coast Software||West Coast Software Limited,Everyone 10+,3,70,0,2,0,0
1,10,g-prime,G Prime Into The Rain,NaN,2016-01-06,False,2019-11-06T23:04:19,NaN,0.0,0,...,Soma Games,Simulation||Indie,Code-Monkeys||Code-Monkeys LLC||Immanitas Ente...,Everyone,0,39,0,1,0,0
2,100,land-sliders,Land Sliders,NaN,2015-09-24,False,2019-10-22T13:56:16,http://prettygreat.com,0.0,0,...,Prettygreat Pty. Ltd.,Adventure||Arcade,Prettygreat Pty. Ltd.,Everyone 10+,0,0,1,1,1,0
3,1000,pixel-gear,Pixel Gear,NaN,2016-10-20,False,2019-08-28T22:16:02,https://www.facebook.com/Geronimo-Interactive-...,0.0,0,...,Oasis Games Limited||Geronimo Interactive,Action||Indie,Geronimo Interactive,Teen,0,0,0,2,0,0
4,10000,gods-and-idols,Gods and Idols,NaN,2016-12-12,False,2019-09-17T13:37:13,http://www.godsandidols.com/,0.0,0,...,Viking Tao,RPG||Strategy||Massively Multiplayer,Viking Tao,NaN,1,57,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345662,99994,holy-or-dead,Holy or Dead,NaN,2017-05-17,False,2019-01-09T12:41:06,NaN,0.0,0,...,Ralidon,NaN,NaN,NaN,0,0,0,0,0,0
345663,99995,airstrike-hd-demo,Airstrike HD Demo,NaN,2016-03-04,False,2019-01-09T12:41:06,NaN,0.0,0,...,Fifth Dimension Company,Action,NaN,NaN,0,0,0,0,0,0
345664,99997,uranias-mirror,Urania's Mirror,NaN,2016-04-25,False,2019-01-09T12:41:06,NaN,0.0,0,...,sneakthief,Adventure,NaN,NaN,0,0,0,0,0,0
345665,99998,simucities,Simucities,NaN,2017-05-26,False,2019-01-09T12:41:06,NaN,0.0,0,...,keypixels,NaN,NaN,NaN,0,0,0,0,0,0
345666,99999,pocket-assault,Pocket Assault (itch),NaN,2015-08-20,False,2019-01-09T12:41:06,NaN,0.0,0,...,Carsten_Ostermann,Shooter,NaN,NaN,0,0,0,0,0,0

In [34]:
# filter the release_date
Game = Game.filter(regex='....-*-*', axis=0)

In [37]:
# Game

In [36]:
Game.to_csv("Game.csv", index=False)

In [26]:
# clean Game_genre
Game_genre = Game_origin[["id", "genres"]]
Game_genre = pd.merge(Game, Game_genre, how='left')[["id", "genres"]]
Game_genre = Game_genre.fillna("Other")
Game_genre["genres"] = Game_genre["genres"].str.split("\|\|")
Game_genre = Game_genre.explode("genres").reset_index()[["id", "genres"]]

In [50]:
# Game_genre

            id      genres
0            1   Adventure
1            1      Puzzle
2            2      Action
3            2   Adventure
4            2      Casual
...        ...         ...
449038  388932       Other
449039  388933  Platformer
449040  388935      Action
449041  388935   Adventure
449042  388935         RPG

[449043 rows x 2 columns]

In [28]:
# clean Genre
Genre = Game_genre[["genres"]]
Genre = Genre.sort_values(by=['genres'])
Genre = Genre[["genres"]].drop_duplicates().dropna().reset_index()[["genres"]]
Genre = Genre.rename(columns={'genres': 'name'})

In [31]:
#Genre

In [30]:
# extract Game_genre and Genre to Game_genre.csv and Genre.csv respectively
Game_genre.to_csv("Game_genre.csv", index=False)
Genre.to_csv("Genre.csv", index=False)

In [38]:
# clean Game_reviews_origin 
Game_reviews_origin['website_rating'] = Game_reviews_origin['website_rating'].str.replace('None', '')
Game_reviews_origin['website_rating'] = Game_reviews_origin['website_rating'].str.replace(',', '')
Game_reviews_origin['website_rating'] = Game_reviews_origin['website_rating'].str.replace('-', '')
Game_reviews_origin['user_rating'] = Game_reviews_origin['website_rating'].str.replace('None', '')
Game_reviews_origin['user_rating'] = Game_reviews_origin['website_rating'].str.replace(',', '')
Game_reviews_origin['user_rating'] = Game_reviews_origin['website_rating'].str.replace('-', '')
Game_reviews_origin['website_rating'] = pd.to_numeric(Game_reviews_origin['website_rating'])
Game_reviews_origin['user_rating'] = pd.to_numeric(Game_reviews_origin['user_rating'])

In [43]:
Game_reviews_origin

,id,game,platform,website_rating,user_rating,release,developer,classification,preview,url
0,1,¡Has sido tú!,PS4,7.5,7.5,4/7/2017,Wish Studios & Sony,PEGI +12,La razón por la que han existido las consolas ...,https://vandal.elespanol.com/analisis/ps4/has-...
1,2,#IDARB,Xbox One,8.2,8.2,3/2/2015,Other Ocean Interactive,PEGI +3,"Es un fenómeno curioso, pero bien podríamos de...",https://vandal.elespanol.com/analisis/xbone/id...
2,3,007 Racing,PS One,6.9,6.9,Enero 2001,EA Games & Electronic Arts,None,"Bond, James BondCon la reciente tirada de títu...",https://vandal.elespanol.com/analisis/psx/007-...
3,4,007: Agente en Fuego Cruzado,GameCube,7.7,7.7,Año 2002,EA Games & Electronic Arts,None,"No podía ser de otra maneraBond vuelve, no pod...",https://vandal.elespanol.com/analisis/gcn/007-...
4,5,007: Nightfire,GameCube,8.7,8.7,29/11/2002,Eurocom & EA Games,None,Licencia para matarAunque son muchos los jueg...,https://vandal.elespanol.com/analisis/gcn/007-...
...,...,...,...,...,...,...,...,...,...,...
11905,11906,Zookeeper Battle!,iPhone,7.5,7.5,23/8/2012,Kiteretsu,PEGI +3,Los juegos de puzles siguen teniendo una imper...,https://vandal.elespanol.com/analisis/android/...
11906,11907,Zuki's Quest,Android,7.5,7.5,22/11/2013,Arnold Floeck & Tinytouchtales,None,No engañaremos a nadie si decimos que en la Ap...,https://vandal.elespanol.com/analisis/android/...
11907,11908,Zuki's Quest,iPhone,7.5,7.5,22/11/2013,Arnold Floeck & Tinytouchtales,None,No engañaremos a nadie si decimos que en la Ap...,https://vandal.elespanol.com/analisis/android/...
11908,11909,Zuma's Revenge! XBLA,Xbox 360,8.0,8.0,11/7/2012,PopCap Games,PEGI +7,Nadie duda en estos momentos que el mercado de...,https://vandal.elespanol.com/analisis/x360/zum...
11909,11910,Zumba Fitness Core,Xbox 360,8.0,8.0,8/11/2012,Pipeworks Software & Majesco Entertainment,PEGI +3,En apenas dos años la serie Zumba Fitness ha v...,https://vandal.elespanol.com/analisis/x360/zum...

In [142]:
# merge Game_reviews_origin and Game to find the user and website rating of the games 

Rating = pd.merge(Game, Game_reviews_origin, left_on='name', right_on='game', how='left')[['id_x', 'website_rating', 'user_rating']]
Rating = pd.merge(Game_genre, Rating, left_on='id', right_on='id_x', how='inner')[['id', 'website_rating', 'user_rating', 'genres']]
Rating['website_rating'] = np.where(Rating['website_rating']>10, Rating['website_rating']/10, Rating['website_rating'])
Rating['user_rating'] = np.where(Rating['user_rating']>10, Rating['user_rating']/10, Rating['user_rating'])
random.seed(9527)
Rating = Rating.groupby("genres").transform(lambda x: x.fillna(x.mean() - random.uniform(0, 2.0)))
Rating = Rating.groupby('id').mean().reset_index()
Rating = Rating.round(1)

In [145]:
# Rating

In [146]:
# extract Rating to csv file 
Rating.to_csv("Rating.csv", index=False)

In [91]:
# clean website of the games 
Game_sales_origin["img_url"] = "http://www.vgchartz.com" + Game_sales_origin["img_url"]
Website = pd.merge(Game, Game_sales_origin, left_on='name', right_on='Name', how='inner')
Website = Website[['id', 'url', 'img_url']].sort_values(by='id').drop_duplicates(subset='id').reset_index(drop=True)
Website = Website.rename(columns={'url': 'vg_url', 'img_url': 'photo_url'})

In [92]:
# export Website to Website.csv
Website.to_csv("Website.csv", index=False)

In [93]:
Website

,id,vg_url,photo_url
0,1064,http://www.vgchartz.com/game/137625/hatsune-mi...,http://www.vgchartz.com/games/boxart/default.jpg
1,1065,http://www.vgchartz.com/game/222831/headmaster...,http://www.vgchartz.com/games/boxart/full_3381...
2,1067,http://www.vgchartz.com/game/142336/here-they-...,http://www.vgchartz.com/games/boxart/full_9307...
3,1071,http://www.vgchartz.com/game/169960/job-simula...,http://www.vgchartz.com/games/boxart/full_2628...
4,1077,http://www.vgchartz.com/game/221591/teslagrad/...,http://www.vgchartz.com/games/boxart/full_3810...
...,...,...,...
13579,386807,http://www.vgchartz.com/game/18871/twin/?regio...,http://www.vgchartz.com/games/boxart/full_twin...
13580,387420,http://www.vgchartz.com/game/23142/space-shutt...,http://www.vgchartz.com/games/boxart/49584ccc.jpg
13581,387852,http://www.vgchartz.com/game/3548/july/?region...,http://www.vgchartz.com/games/boxart/full_9080...
13582,388325,http://www.vgchartz.com/game/79249/coffee-rush...,http://www.vgchartz.com/games/boxart/default.jpg
13583,388928,http://www.vgchartz.com/game/29813/zombie-atta...,http://www.vgchartz.com/games/boxart/full_7087...

In [95]:
Game_plat = Game_origin[['id', 'platforms']]
Game_plat = pd.merge(Game, Game_plat, how='left')[['id', 'platforms']]
Game_plat = Game_plat.fillna("Other")
Game_plat["platforms"] = Game_plat["platforms"].str.split("\|\|")
Game_plat = Game_plat.explode("platforms").reset_index()[['id', 'platforms']]

Platforms = Game_plat[['platforms']]
Platforms = Platforms.sort_values(by=['platforms'])
Platforms = Platforms[['platforms']].drop_duplicates().dropna().reset_index()[["platforms"]]
Platforms

             platforms
0                  3DO
1              Android
2             Apple II
3           Atari 2600
4           Atari 5200
5           Atari 7800
6          Atari 8-bit
7      Atari Flashback
8           Atari Lynx
9             Atari ST
10          Atari XEGS
11   Classic Macintosh
12   Commodore / Amiga
13           Dreamcast
14            Game Boy
15    Game Boy Advance
16      Game Boy Color
17           Game Gear
18            GameCube
19             Genesis
20              Jaguar
21               Linux
22                 NES
23             Neo Geo
24        Nintendo 3DS
25         Nintendo 64
26         Nintendo DS
27        Nintendo DSi
28     Nintendo Switch
29               Other
30                  PC
31             PS Vita
32                 PSP
33         PlayStation
34       PlayStation 2
35       PlayStation 3
36       PlayStation 4
37            SEGA 32X
38             SEGA CD
39  SEGA Master System
40         SEGA Saturn
41                SNES
42                 Web
43                 Wii
44               Wii U
45                Xbox
46            Xbox 360
47            Xbox One
48                 iOS
49                 mac
50               macOS

In [102]:
Game_class = pd.merge(Game, Game_reviews_origin, left_on = 'name', right_on = 'game', how = 'left')[['id_x', 'classification']]
Game_class = Game_class.rename(columns = {'id_x': 'id'})
Game_class = Game_class.fillna("None")
Game_class = Game_class.drop_duplicates().sort_values(by=['id']).reset_index(drop = True)
Game_class.to_csv("Game_class.csv", index = False)

Classification = Game_class[['classification']]
Classification = Classification.drop_duplicates().reset_index(drop = True)
Classification.to_csv("Classification.csv", index = False)

In [103]:
Game_class

            id classification
0         1061           None
1         1063           None
2         1064           None
3         1065           None
4         1066           None
...        ...            ...
309512  388930           None
309513  388931           None
309514  388932           None
309515  388933           None
309516  388935           None

[309517 rows x 2 columns]

In [98]:
Classification

  classification
0        PEGI +7
1       PEGI +12
2           None
3       PEGI +18
4       PEGI +16
5        PEGI +3

            id
0         1061
2         1063
13        1064
14        1065
16        1066
...        ...
426801  388930
426802  388931
426803  388932
426806  388933
426807  388935

[309514 rows x 1 columns]

In [150]:
Platforms.to_csv("Platforms.csv", index = False)

In [151]:
Game_plat.to_csv("Game_plat.csv", index = False)